package enums

const View = "View"
const Add = "Add"
const Edit = "Edit"
const Delete = "DeleteBySettingProductID"
const Approve = "Approve"

const Gallery = "galery"
const Faq = "faq"
const Testimoni = "testimoni"
const Article = "article"

const ValuePackagePromotionEnum1 = "Per Hari"
const KeyPackagePromotionEnum1 = "per_hari"
const ValuePackagePromotionEnum2 = "Per Bundle"
const KeyPackagePromotionEnum2 = "per_bundle"

const ValuePlatformEnum1 = "Semua"
const KeyPlatformEnum1 = "semua"
const ValuePlatformEnum2 = "Mobile Apps"
const KeyPlatformEnum2 = "mobile_apps"
const ValuePlatformEnum3 = "Web Compro"
const KeyPlatformEnum3 = "web_compro"

const ValuePromotionPositionEnum1 = "Slider 1"
const KeyPromotionPositionEnum1 = "slider_1"
const ValuePromotionPositionEnum2 = "Slider 2"
const KeyPromotionPositionEnum2 = "slider_2"
const ValuePromotionPositionEnum3 = "Slider 3"
const KeyPromotionPositionEnum3 = "slider_3"
const ValuePromotionPositionEnum4 = "Slider 4"
const KeyPromotionPositionEnum4 = "slider_4"
const ValuePromotionPositionEnum5 = "Slider 5"
const KeyPromotionPositionEnum5 = "slider_5"

const KeySubscriptionEnum1 = "subscription"
const ValueSubscriptionEnum1 = "Subscription"
const KeySubscriptionEnum2 = "webinar"
const ValueSubscriptionEnum2 = "Webinar"
const KeySubscriptionEnum3 = "website"
const ValueSubscriptionEnum3 = "website"

const KeyPriceUnitEnum1 = "hari"
const ValuePriceUnitEnum1 = "Hari"
const KeyPriceUnitEnum2 = "jam"
const ValuePriceUnitEnum2 = "Jam"
const KeyPriceUnitEnum3 = "jamaah"
const KeyPriceUnitEnum4 = "website"

const KeyDiscountTypeEnum1 = "per_hari"
const ValueDiscountTypeEnum1 = "Per Hari"
const KeyDiscountTypeEnum2 = "fix"
const ValueDiscountTypeEnum2 = "Fix"

const KeyComplaintStatusEnum1="open"
const ValueComplaintStatusEnum1="Open"
const KeyComplaintStatusEnum2="close"
const ValueComplaintStatusEnum2 ="Close"
